// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs7Yn0m6Chn6fkV5pF_5G--LrXBc6KCNI',
    appId: '1:911250800566:web:deec3cb26165f016ac4b17',
    messagingSenderId: '911250800566',
    projectId: 'swiftpay-61b00',
    authDomain: 'swiftpay-61b00.firebaseapp.com',
    storageBucket: 'swiftpay-61b00.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUV2iP5_zBkjQTrm-UHQXr6tykXpyNxRw',
    appId: '1:911250800566:android:31af126330df0896ac4b17',
    messagingSenderId: '911250800566',
    projectId: 'swiftpay-61b00',
    storageBucket: 'swiftpay-61b00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs7Yn0m6Chn6fkV5pF_5G--LrXBc6KCNI',
    appId: '1:911250800566:ios:5873f788c42c32fdac4b17',
    messagingSenderId: '911250800566',
    projectId: 'swiftpay-61b00',
    storageBucket: 'swiftpay-61b00.firebasestorage.app',
    iosBundleId: 'com.example.swiftpay',
  );
}